### ISSUE TITLE
Navigation par ingrédients impossible

### ISSUE THREAD

**Issue by bpesquet** [polytechlyon-isi2/Home-Burger#1]
L'erreur rend impossible la navigation par catégories
![capture d ecran 2015-06-11 a 16 45 02](https://cloud.githubusercontent.com/assets/1837749/8109834/3db3677a-1059-11e5-9b71-566e52301529.png)

**Comment by flibustier** [comment]
Problème corrigé : Les categories n'étaient pas données au render lors d'un bug
